### ISSUE TITLE
Infinite scroll bug with tx_news pagination

### ISSUE THREAD

**Issue by kzucconi** [jweiland-net/infinitescrolling#5]
I’m on typo3 v7.6.26 with tx_news v6.3.0 and infinitescrolling v2.0.0. I have a bug when I scroll on list view of news with ajax load more, then when I go to the detail view of a news and come back to the list view with the navigator history back, some news have disappeared and it doesn’t display the news of the first page. It only displays the news who were on the same page of the news that I clicked before.

**Comment by froemken** [comment]
Hi @kzucconi 

since 22.02.2018 we have merged Patch #3 which should solve your problem into Version 2.1.0.
Please update your version

Nice greetings

Stefan

**Comment by froemken** [comment]
I have just uploaded version 2.1.0 and 2.2.0 into TER

**Comment by kzucconi** [comment]
Hi thank you for your answer, but I uploaded the new version 2.2.0, but I still have the bug.. :( Is there something more to do for this working?

**Comment by froemken** [comment]
I have just installed TYPO3 7 with news 6.3.
I use following TS configuration:

```
plugin.tx_infinitescrolling.container = div.news-list-view
plugin.tx_infinitescrolling.item = div.article
plugin.tx_infinitescrolling.pagination = div.page-navigation
plugin.tx_infinitescrolling.next = div.page-navigation:eq(1) ul.f3-widget-paginator li.next a
plugin.tx_infinitescrolling.previous = div.page-navigation:eq(1) ul.f3-widget-paginator li.previous a
plugin.tx_infinitescrolling.negativeMargin = -50
```

Further please check if following is set in ObjectBrowser:
```
1519224720.wrap (
  jQuery(function() {
    var ias = jQuery.ias({|});
    ias.extension(new IASSpinnerExtension({
      html: '{$plugin.tx_infinitescrolling.loader}'
    }));
    ias.extension(new IASPagingExtension());
    ias.extension(new IASHistoryExtension({
      prev: '{$plugin.tx_infinitescrolling.previous}'
    }));
  });
  )
```

Please verify that you can find IASHistoryExtension there.

If I use browser "back" my clicked news item has jumped a little bit too high, but yes, I'm nearly at the right place. When I begin to scroll all other news will be loaded again. Regardless, if I scroll up or down.

Maybe it is helpful to send me your TS Constants of infinitescrolling.

Also please check if you will find that line in footer of your sites sourcecode in browser:
typo3conf/ext/infinitescrolling/Resources/Public/JavaScript/Ias/Extension/History.js

Stefan
